version: 2

before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - id: sun
    binary: sun
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    gcflags:
      - all=-trimpath={{.Env.PWD}}
    asmflags:
      - all=-trimpath={{.Env.PWD}}
    tags:
      - netgo
      - osusergo

archives:
  - id: sun-archive
    name_template: >-
      {{ .ProjectName }}-
      {{- .Version }}-
      {{- .Os }}-
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    format: tar.gz
    files:
      - README.md
      - LICENSE*

# Create standalone binaries for easy install script usage
release:
  github:
    owner: '{{ .Env.GITHUB_REPOSITORY_OWNER }}'
    name: '{{ .ProjectName }}'
  name_template: '{{ .Version }}'
  prerelease: auto
  draft: false
  replace_existing_draft: true
  make_latest: true
  mode: append
  header: |
    ## Installation

    ### macOS

    Quick install using our script:
    ```bash
    curl -fsSL https://raw.githubusercontent.com/{{ .Env.GITHUB_REPOSITORY }}/main/install.sh | bash
    ```

    Or manually download for your architecture:
    - **Apple Silicon (M1/M2/M3/M4)**: Download `sun-darwin-arm64`
    - **Intel Mac**: Download `sun-darwin-amd64`

    Then:
    ```bash
    chmod +x sun-darwin-*
    sudo mv sun-darwin-* /usr/local/bin/sun
    ```

    ### Using Homebrew (coming soon)
    ```bash
    brew tap YOUR_USERNAME/tap
    brew install sun
    ```
  footer: |
    ## Changelog

    See [CHANGELOG.md](https://github.com/{{ .Env.GITHUB_REPOSITORY }}/blob/main/CHANGELOG.md) for details.

    ## Checksums

    Verify your download:
    ```bash
    shasum -a 256 -c sun_{{ .Version }}_checksums.txt
    ```
  extra_files:
    # Create simple binaries without archive wrapping
    - glob: ./dist/sun_darwin_amd64_v1/sun
      name_template: 'sun-darwin-amd64'
    - glob: ./dist/sun_darwin_arm64/sun
      name_template: 'sun-darwin-arm64'

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_checksums.txt'
  algorithm: sha256

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - 'typo'
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Bug Fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Performance Improvements
      regexp: '^.*?perf(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: Others
      order: 999

snapshot:
  name_template: '{{ incpatch .Version }}-next'

metadata:
  mod_timestamp: '{{ .CommitTimestamp }}'
